### ISSUE TITLE
演示网站怎么打不开了

### ISSUE THREAD

**Issue by wangrfx** [jielive/initial#14]
想问一下links的内容怎么写  想看一下主题的相关使用说明

**Comment by xiaoaozhi3** [comment]
1. 创建一个独立页面，模板选择“链接”。
2. 找到“自定义字段”下面的“links”。
3. 按以下规则填写（英文逗号）
名称，地址，描述，图标
4. 每一条以回车区分。


这是部分源码
```php
list($name, $url, $description, $logo, $sort) = explode(',', $val);
```

**Comment by xiaoaozhi3** [comment]
> 想问一下links的内容怎么写 想看一下主题的相关使用说明

1. 创建一个独立页面，模板选择“链接”。
2. 找到“自定义字段”下面的“links”。
3. 按以下规则填写（英文逗号）
名称，地址，描述，图标
4. 每一条以回车区分。


这是部分源码
```php
list($name, $url, $description, $logo, $sort) = explode(',', $val);
```

**Comment by jkfx** [comment]
> 想问一下links的内容怎么写 想看一下主题的相关使用说明
